apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-pvc-dynamic-bk
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
