apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-huge-req
spec:
  containers:
  - image: ghcr.io/c1t1d0s7/go-myweb:alpine
    name: myapp
    resources:
      requests:
        cpu: 400m
        memory: 4Gi
